version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: accounting
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: accounting

	accounting:
		build: .
		image: chamaconekt/accounting
		links:
		- postgres
		container_name: accounting
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- accounting
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/accounting-nginx/nginx.conf
		depends_on:
			- accounting
		ports:
			- 80:80
		volumes_from:
			- accounting

volumes:
	accounting-static-files:
		driver:local